---
- name: Playbook for configuring my site
  hosts: all
  become: true

  vars:
    docker_users:
      - "{{ ansible_user }}"

  roles:
    - server_laptop
    - accessibility
    - docker
    - devtools
    - system_upgrade
