---
- name: Install Docker
  community.general.pacman:
    name: docker
    state: present
    update_cache: true

- name: Enable Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add ansible_user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
