---
- name: Playbook for configuring my site
  hosts: all
  become: true

  vars:
    docker_users:
      - "{{ ansible_user }}"

  tasks:
    - name: Server_laptop
      ansible.builtin.include_role:
        name: server_laptop
      when: server_laptop_enabled | default(false)
    - name: Change ansible_user's shell to /usr/bin/fish
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/fish
      when: false
  roles:
    - accessibility
    - docker
    - packagesync
    - shell
